<a href="https://colab.research.google.com/github/purnimasharma04/Task2_AICLUB/blob/main/numpybasics_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myPythonList = [1,2,3,4]
print(myPythonList)

[1, 2, 3, 4]


In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list


array([1, 2, 3, 4])

In [ ]:
a  = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
x=numpy_array_from_list + 10
print(x)

[11 12 13 14]


Shape of Array


In [ ]:
a  = np.array([4,5,6])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
#### Different type
b  = np.array([4.1,5.0,6.2])
print(b.dtype)

float64


In [ ]:
### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
### 3 dimension
d = np.array([
    [[1,2,3],
        [4, 5, 6]],
    [[7, 13,9],
        [50, 8, 21]]
])
print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7 13  9]
  [50  8 21]]]


numpy.zeroes


In [ ]:
import numpy as np
x=np.zeros((10,10), dtype=np.int16)
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
import numpy as np
y=np.ones((1,2,3,4), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3, 4)
[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]]


reshape data


In [ ]:
import numpy as np
e  = np.array([(4,5,6), (1,2,3)])
print(e)
e.reshape(3,2)

[[4 5 6]
 [1 2 3]]


array([[4, 5],
       [6, 1],
       [2, 3]])

In [ ]:
Flatten data

In [ ]:
e.flatten()

array([4, 5, 6, 1, 2, 3])

Hstack

In [ ]:
## Horitzontal Stack
import numpy as np
f = np.array([4,5,6])
g = np.array([1,2,3])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [4 5 6 1 2 3]


Vstack

In [ ]:
## Vertical Stack
import numpy as np
f = np.array([4,5,6])
g = np.array([1,2,3])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[4 5 6]
 [1 2 3]]


random numbers


In [ ]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)			


[5.18530745 5.56678322 4.71520138 5.16249592 4.76247705 4.60781596
 5.58791128 4.72006274 5.23236324 4.90717716]


assray

In [ ]:
A = np.matrix(np.ones((6,7)))		
print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


numpyarange

In [ ]:
np.arange(1, 12)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(1, 14, 5)	

array([ 1,  6, 11])

linspace


In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

logspace

In [ ]:
np.logspace(4.0, 5.0, num=4)

array([ 10000.        ,  21544.34690032,  46415.88833613, 100000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

slicing


In [ ]:
## Slice
import numpy as np
e  = np.array([(53,5,6), (12,8,6)])
print(e)


[[53  5  6]
 [12  8  6]]


In [ ]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [53  5  6]
Second row: [12  8  6]


In [ ]:

print('Second column:', e[:,1])	



Second column: [5 8]


In [ ]:
## Second Row, two values
print(e[1, :2])

[12  8]


In [ ]:
#Second column 2 values
print(e[:2,1])

[5 8]


numpy

In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	



[5.38455528 4.41864576 5.93534727 4.38410915 5.80644346 4.93103151
 5.96857878 5.64935508 5.25634509 4.93515671]


In [ ]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.384109145600804
5.968578781224481
5.2669568077791
5.320450182994023
0.5578731253376469


dotproduct

In [ ]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([6,3])
g = np.array([4,5])
### 6*3+2*5
np.dot(f, g)

39

multiplication

In [ ]:

### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)


array([[19, 22],
       [43, 50]])

inverse


In [ ]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


matrix


In [ ]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


rank


In [ ]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[0,0,0],[0,0,0],[0,0,0]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

0

eigenvalues and vectors

In [ ]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


diagonal

In [ ]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


transpose


In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


trace

In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]
